### ISSUE TITLE
Serial Connection to MP3-TF-16P

### ISSUE THREAD

**Issue by savall21** [bablokb/circuitpython-dfplayer#2]
There is a DFPlayer Mini clone called MP3-TF-16P.  They look the same but use different chips.  The hardware based triggers work. However, I can't get the serial connection to work.  When I use code that work on the original I get an error "DFPlayer could not be initialized".  The serial connection fails.  Any help appreciated!

**Comment by bablokb** [comment]
I don't have this hardware, so it is hard to tell which problem you have. I would suggest that you add some print-statements in the lib to gain insights.

**Comment by savall21** [comment]
Thanks for the response. I did some more digging and the new chips definitely operate differently.  Apparently the Serial connection has to be started with a zero checksum???  Here's a response on Amazon with code that apparently works:

As others have posted, THESE boards don't allow the standard libraries for DFMiniPlayers to work. They DO allow the "standalone" use -- that is, you can use the pins for "next track" and "previous track" and give them a 1 or 2 second "low" signal to raise or lower the volume. They do pump out really good volume on even tiny speakers, which is great. I'm using them in puzzles which only require one track to ever play, so they're fine for me. Send a 50ms LOW pulse to the right pin, and it works fine.

EDIT:
I put in the hours to figure out how to get the serial commands to work, and here's everything, if you want to use an Arduino or (in my case) a Wemos D1 Mini board, using the Arduino IDE...

1: It doesn't use any of the libraries available, it only uses SoftwareSerial, and the Serial commands to make it work.
2: Unlike the "real" boards, you DO NOT USE the checksum bytes in the commands.
3: Powering the board from the 5v pin works fine (if you're using the USB power to connect to your computer).
4: Using an external 5v power supply can power the Wemos and the DF Player board just fine.
5: If you want to be able to use a command to play a particular track, by the number/name you give it and NOT the order it was burned to the SD card, DO THIS: Format the SD card as FAT, create a folder "01" on the root level on it, and name the files in these conventions: Either "001.wav" (or .mp3) and/or "001_myFileName.wav" ... when you command the file to play, you'll be using the "0x0F" (Play Folder) command and NOT NOT NOT the "0x03" (Specify Track) command.

Here's a barebones file which starts things up (you tell it to "play" and then stop, and that essentially turns the board into play mode -- like playing a track zero for 2/10ths of a second), and then plays a few specific tracks and then repeats. Just to show you how it's done, and not in "order" of the files or file numbers.

`/*
THIS WORKS WITH THE FAKE DFPLAYERS
on a wemos D1

On SD card, have folder "01" and then files must be 001.wav or 001_myFile.mp3 etc
Will work by NAME no matter what order they're written on disk. Must use playfolder (and file) command,
NOT simply playfile.
*/

#include <SoftwareSerial.h>
SoftwareSerial mySerial(D5, D6); // RX, TX... D5 goes to 3rd pin down, D6 goes to 2nd pin down from top

void sendCmd(int cmd, int lb, int hb, bool reply = false)
{ // standard format for module command stream
uint8_t buf[] = {0x7E, 0xFF, 0x00, 0x00, 0x00, 0x00, 0x00, 0xEF};
int16_t chksum = 0;
int idx = 3; // position of first command byte

buf[idx++] = (uint8_t)cmd; // inject command byte in buffer
if (reply) buf[idx++] = 0x01;
else buf[idx++] = 0x00;// set if reply is needed/wanted
if (hb >= 0) // if there is a high byte data field
buf[idx++] = (uint8_t)hb; // add it to the buffer
if (lb >= 0) // if there is a low byte data field
buf[idx++] = (uint8_t)lb; // add it to the buffer
buf[2] = idx - 1; // inject command length into buffer
buf[idx++] = 0xEF; // place end-of-command byte

mySerial.write(buf, idx); // send the command to module
// for (int i = 0; i < idx; i++) // send command as hex string to MCU
// Serial.printf("%02X ", buf[i]);
// Serial.println();
}

void setup()
{
Serial.begin(115200); //for console debugging
delay(2000); //Allow Serial to start up

Serial.println("starting ");
mySerial.begin(9600); //communicate with DF Player
delay(3000); //Allow SoftwareSerial to start up

Serial.println("Stop anything playing"); //in case anything is already playing on reset
sendCmd(0x0E, 0, 0, false);
delay(200); //give a delay for the DF Player to execute the command

Serial.println("Now volume ");
sendCmd(6, 5, 0, false); //command code can be in decimal too.

Serial.println("Starting Player");
sendCmd(0x01, 0, 0, false); // Send a "next track" command that turns play mode on
delay(1000);
Serial.println("_____________________________________");

}

void loop()
{
Serial.println("play track 3 ");
sendCmd(0x0F, 3, 1, false); //play track 003 in folder 01
delay(8000);
sendCmd(0x0E, 0, 0, false); //send stop command
delay(200);
Serial.println(" ");

Serial.println("play track 5 ");
sendCmd(0x0F, 5, 1, false); //play track 005 in folder 01
delay(8000);
sendCmd(0x0E, 0, 0, false); //send stop command
delay(200);
Serial.println(" ");

Serial.println("play track 1 ");
sendCmd(0x0F, 1, 1, false); //play track 001 in folder 01
delay(8000);
sendCmd(0x0E, 0, 0, false); //send stop command
delay(200);
Serial.println(" ");

Serial.println("play track 6 ");
sendCmd(0x0F, 6, 1, false); //play track 006 in folder 01
delay(8000);
sendCmd(0x0E, 0, 0, false); //send stop command
delay(200);
Serial.println(" ");
}`

I'm just not sure how to implement that change in circuitpython.

**Comment by bablokb** [comment]
closing this because the code in this repo is not for that device.
