### ISSUE TITLE
loop overloaded in a non functional way

### ISSUE THREAD

**Issue by danielw1990** [bablokb/circuitpython-dfplayer#5]
I found that loop is overloaded in a a way that only ever uses the loop over all files command, I applied the simple fix of renaming the looping over all files to "loop_all"

`def loop(self,on=True):`
to:
`def loop_all(self,on=True):`

Related note: Is there  a way to just stop the looping? (without stopping playback)

**Comment by bablokb** [comment]
Oh yes, thanks for reporting the issue.

Regarding the related note: I don't think this is possible. The CircuitPython code just controls the device and I did not find any function there to stop only the looping.

**Comment by bablokb** [comment]
Fixed with https://github.com/bablokb/circuitpython-dfplayer/commit/46e7fa2d4266a309d199d18eb36e2ea5f1cc40b3
